// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DealerDatabase.Data;

#nullable disable

namespace DealerDatabase.Data.Migrations
{
    [DbContext(typeof(DealerDbContext))]
    partial class DealerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DealerDatabase.Data.Entities.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvgDaysInStock")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AvgListedPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AvgSoldPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("FcaReferenceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("FcaStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinanceCalculator")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinanceLendersJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IcoExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IcoRegistrationNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IncorporationDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InventoryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegalCompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryWebsite")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredAddressLine1")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredAddressLine2")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredAddressLine3")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredCounty")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredPostcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepresentativeApr")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SafExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SafStatus")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SoldLast30Days")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TradingAddressLine1")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingAddressLine2")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingAddressLine3")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingCounty")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingPostcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatValidationStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleTypes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyNumber");

                    b.HasIndex("FcaReferenceNumber");

                    b.HasIndex("RegisteredPostcode");

                    b.HasIndex("TradingPostcode");

                    b.HasIndex("VatNumber");

                    b.ToTable("Dealers");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerDirector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AppointedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("DealerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResignedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("MergeNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceRecordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DealerId", "Name", "Role")
                        .IsUnique();

                    b.HasIndex("SourceRecordId");

                    b.ToTable("DealerDirectors");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerFieldSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DealerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DealerId", "FieldName", "SourceRecordId")
                        .IsUnique();

                    b.HasIndex("SourceRecordId");

                    b.ToTable("DealerFieldSources");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerSourceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DealerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchEvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MatchConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("RawDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("SourceType", "SourceKey")
                        .IsUnique();

                    b.ToTable("DealerSourceRecords");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerTradingName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DealerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceRecordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DealerId", "SourceRecordId", "Name")
                        .IsUnique();

                    b.HasIndex("SourceRecordId");

                    b.ToTable("DealerTradingNames");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerDirector", b =>
                {
                    b.HasOne("DealerDatabase.Data.Entities.Dealer", "Dealer")
                        .WithMany("Directors")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealerDatabase.Data.Entities.DealerSourceRecord", "SourceRecord")
                        .WithMany("Directors")
                        .HasForeignKey("SourceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");

                    b.Navigation("SourceRecord");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerFieldSource", b =>
                {
                    b.HasOne("DealerDatabase.Data.Entities.Dealer", "Dealer")
                        .WithMany("FieldSources")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealerDatabase.Data.Entities.DealerSourceRecord", "SourceRecord")
                        .WithMany("FieldSources")
                        .HasForeignKey("SourceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");

                    b.Navigation("SourceRecord");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerSourceRecord", b =>
                {
                    b.HasOne("DealerDatabase.Data.Entities.Dealer", "Dealer")
                        .WithMany("SourceRecords")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerTradingName", b =>
                {
                    b.HasOne("DealerDatabase.Data.Entities.Dealer", "Dealer")
                        .WithMany("TradingNames")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealerDatabase.Data.Entities.DealerSourceRecord", "SourceRecord")
                        .WithMany("TradingNames")
                        .HasForeignKey("SourceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");

                    b.Navigation("SourceRecord");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.Dealer", b =>
                {
                    b.Navigation("Directors");

                    b.Navigation("FieldSources");

                    b.Navigation("SourceRecords");

                    b.Navigation("TradingNames");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerSourceRecord", b =>
                {
                    b.Navigation("Directors");

                    b.Navigation("FieldSources");

                    b.Navigation("TradingNames");
                });
#pragma warning restore 612, 618
        }
    }
}
